#! /usr/bin/python
import yaml
import sys
import re
from os.path import join as joinpath

def main():
	data = StardewData("Unpacked")
	#crop_yaml = load_yaml("Unpacked/Data/Crops.yaml")
	#object_yaml = load_yaml("Unpacked/Data/ObjectInformation.yaml")

	#crops_raw = load_and_expand_yaml_tree("Unpacked/Data/Crops.yaml")
	#import pprint
	#pp = pprint.PrettyPrinter()
	#print pp.pprint(crops_raw)

def load_yaml_tree(filename):
	with open(filename) as f:
		return yaml.load(f)

def extract_content(yaml_tree):
	if 'content' in yaml_tree:
		return yaml_tree['content']
	sys.stderr.write("Warning: Tree does not contain a 'content' node.")
	return yaml_tree

def fix_type(x):
	if len(x) == 0:
		return x
	if re.match("-?[0-9]*$", x) is not None:
		return int(x)
	return x

def expand_slashes_tree(yaml_node):
	if isinstance(yaml_node, dict):
		return { k: expand_slashes_tree(v) for (k,v) in yaml_node.iteritems() }
	elif isinstance(yaml_node, list):
		return [ expand_slashes_tree(n) for n in yaml_node ]
	elif isinstance(yaml_node, (str,unicode)):
		pieces = yaml_node.split("/")	
		pieces = [ fix_type(x) for x in pieces ]
		if len(pieces) == 1:
			return pieces[0]
		return pieces
	else:
		sys.stderr.write("Skipping unknown type {0}".format(type(yaml_node)))
		return yaml_node

def load_and_expand_yaml_tree(filename):
	yaml_tree = load_yaml_tree(filename)
	yaml_tree = extract_content(yaml_tree)
	yaml_tree = expand_slashes_tree(yaml_tree)
	return yaml_tree



class StardewCrop:
	def __init__(self, id, croprecord, objinfo_raw):

		objrecord = objinfo_raw[id]

		self.seed_id = id
		self.seed_name = objrecord[0]

		self.growth_days = [ int(x) for x in croprecord[0].split(" ") ] # Grow cylce? Days in each stage, starting with planted seed?
		croprecord[0] # String of space seperated integers

		seasons = croprecord[1].split(" ")
		self.season_spring = True if 'spring' in seasons else False
		self.season_summer = True if 'summer' in seasons else False
		self.season_fall = True if 'fall' in seasons else False
		self.season_winter = True if 'winter' in seasons else False

		self.image_index = croprecord[2] # Number
		self.plant_id = croprecord[3] # Plant ID
		self.regrowth_days = croprecord[4]
		if self.regrowth_days == -1:
			self.regrowth_days = None
		self.need_scytheqq = True if croprecord[5] == 1 else False

		if croprecord[6] == 'false':
			(tmp1, tmp2, tmp3, tmp4, tmp5) = (False, None, None, None, None)
			self.UNKNOWN6 = False
			self.UNKNOWN6a = None
			self.UNKNOWN6b = None
			self.UNKNOWN6c = None
			self.UNKNOWN6d = None
		elif croprecord[6].find("true ") == 0:
			(tmp1, tmp2, tmp3, tmp4, tmp5) = croprecord[6].split(" ")
			self.UNKNOWN6 =  True
			self.UNKNOWN6a = int(tmp2)
			self.UNKNOWN6b = int(tmp3)
			self.UNKNOWN6c = int(tmp4)
			self.UNKNOWN6d = float(tmp5)
		else:
			sys.stderr.write("Unable to parse crop record field 6: "+croprecord[6])
			sys.exit(1)

		self.impassible = True if croprecord[7] == "true" else False

		self.UNKNOWN8 = croprecord[8] # true/false + numbers if true?

		#print repr(objinfo_raw.keys())
		#print repr(self.plant_id)
		#sys.exit(1)

		plant_obj_record = objinfo_raw[self.plant_id]
		self.crop_name = plant_obj_record[0]
		self.plant_base_sell_price = plant_obj_record[1]
		self.plant_UNKNOWN2 = plant_obj_record[2] # int?
		self.plant_UNKNOWN3 = plant_obj_record[3] # "Basic -##" or "Seeds -##"
		self.plant_description = plant_obj_record[4] # 

	def __str__(self):
		return "\t".join([ str(x) for x in [
			self.seed_id,
			self.seed_name,
			self.growth_days,
			self.regrowth_days,
			"spring" if self.season_spring else ".",
			"summer" if self.season_summer else ".",
			"fall" if self.season_fall else ".",
			"winter" if self.season_winter else ".",
			#self.image_index,
			"scythe" if self.need_scytheqq else "hand",
			self.UNKNOWN6,
			"(",
			self.UNKNOWN6a,
			self.UNKNOWN6b,
			self.UNKNOWN6c,
			self.UNKNOWN6d,
			")",
			"impassible" if self.impassible else ".",
			self.UNKNOWN8,
			"->",
			self.plant_id,
			self.crop_name,
			str(self.plant_base_sell_price)+"g",
			self.plant_UNKNOWN2,
			self.plant_UNKNOWN3,
			#self.plant_description,
			]
			])

class StardewData:
	def __init__(self, rootdir):
		crops_raw = load_and_expand_yaml_tree(joinpath(rootdir, "Data", "Crops.yaml"))
		objinfo_raw = load_and_expand_yaml_tree(joinpath(rootdir, "Data", "ObjectInformation.yaml"))

		import pprint
		pp = pprint.PrettyPrinter()

		for id in crops_raw:
			crop_record = crops_raw[id]
			o = StardewCrop(id, crop_record, objinfo_raw)
			print o
			#pp.pprint(o)


		#for (id, record) in objinfo_raw.iteritems():
		#	try:
		#		o = StardewObject(id, record)
		#		print o
		#	except:
		#		print "Confusing:", id, "" , pp.pprint(record), "DONE"
		#		raise



		
		

sys.exit(main())

